export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const USER_LIKED_VIDEO_LOADED = "USER_LIKED_VIDEO_LOADED";
export const USER_LIKED_VIDEO_LOADING = "USER_LIKED_VIDEO_LOADING";
export const USER_DISLIKED_VIDEO_LOADED = "USER_DISLIKED_VIDEO_LOADED";
export const USER_DISLIKED_VIDEO_LOADING = "USER_DISLIKED_VIDEO_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOPIC_LOADING = "TOPIC_LOADING";
export const TOPIC_LOADED = "TOPIC_LOADED";
export const SUBTOPICS_LOADED = "SUBTOPICS_LOADED";
export const SUBTOPICS_LOADING = "SUBTOPICS_LOADING";
export const VIDEOS_LOADING = "VIDEOS_LOADING";
export const VIDEO_LOADING = "VIDEO_LOADING";
export const VIDEOS_LOADED = "VIDEOS_LOADED";
export const VIDEO_LOADED = "VIDEO_LOADED";

