export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const TOPIC_LOADING = "TOPIC_LOADING";
export const TOPIC_LOADED = "TOPIC_LOADED";